# ======================== Server ========================
port: 52696
# ===================== LLM Settings =====================
# llm_url: "http://localhost:11434/v1/"
llm_mode: "openai"
llm_url: "http://localhost:11434/"
api_key: "key"
organization_id: "org-id"
project_id:  "proj_id"

model: "gpt-4o" # "llama3-zh-inst" "llama3:latest"  "gpt-4o" "gpt-4o-mini" "gpt-4"
prompts: "test.txt"

revGPT:
  prompts:

memGPT:
  prompts:
# ===================== TTS Settings ====================== 
tts_mode: "vitsTTS" #visTTS, edgeTTS

tts:
  edgeTTS:
    voice: "en-US-EmmaMultilingualNeural" # "en-US-EmmaMultilingualNeural" "zh-TW-HsiaoYuNeural"
    pitch: "+10Hz"

  vitsTTS:
    model_path: "paimon6k_390k.pth"
    config_path: "paimon6k.json"
    speed: 1
    sentiment: True
    sentiment_model_path: "paimon_sentiment.onnx"

# ===================== STT Settings ====================== 
stt_mode: "ASR"

stt:
  sr:
    language: "zh-CN"
    
  ASR:
    config_path: "stt/resources/config.yaml"

bless: False

# 如果要新cfg按照這個格式
# 新的種類:
#   新的設定: "新的值"
#   新的設定2: "新的值"
# 阿如果只有一個就不用了